; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Title screen scene header
; ------------------------------------------------------------------------------
	
	include	"src/shared.inc"
	include	"src/title/variables.inc"
	include	"src/title/data/mars.inc"
	include	"src/title/data/md.inc"
	include	"src/title/maps/maps.inc"

; ------------------------------------------------------------------------------
