; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Splash screen scene header
; ------------------------------------------------------------------------------
	
	include	"src/shared.inc"
	include	"src/splash/variables.inc"
	include	"src/splash/data/mars.inc"
	include	"src/splash/data/md.inc"

; ------------------------------------------------------------------------------
