; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sonic stage map routines header
; ------------------------------------------------------------------------------

	global Init_RingGirl
	global Draw_RingGirl
	global Scroll_RingGirl
	global Init_RingGirlBoss
	global Draw_RingGirlBoss
	global Scroll_RingGirlBoss
	global Init_BenDrowned
	global Draw_BenDrowned
	global Scroll_BenDrowned
	global Init_BenDrownedBoss
	global Draw_BenDrownedBoss
	global Scroll_BenDrownedBoss
	global Init_Slenderman
	global Draw_Slenderman
	global Scroll_Slenderman
	global Init_SlendermanBoss
	global Draw_SlendermanBoss
	global Scroll_SlendermanBoss
	global Init_Hellscape
	global Draw_Hellscape
	global Scroll_Hellscape
	global Init_HellscapeBoss
	global Draw_HellscapeBoss
	global Scroll_HellscapeBoss
	global Init_ScaryMaze
	global Draw_ScaryMaze
	global Scroll_ScaryMaze
	global Init_FinalNormal
	global Draw_FinalNormal
	global Scroll_FinalNormal
	global Init_FinalPrison
	global Draw_FinalPrison
	global Scroll_FinalPrison
	global Init_FinalComputer
	global Draw_FinalComputer
	global Scroll_FinalComputer

; ------------------------------------------------------------------------------
