; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; RPG stage scene header
; ------------------------------------------------------------------------------
	
	include	"source/shared.inc"
	include	"source/rpg/variables.inc"
	include	"source/rpg/cult_front_door.inc"
	include	"source/rpg/cut_to_black.inc"
	include	"source/rpg/good_ending.inc"
	include	"source/rpg/object.inc"
	include	"source/rpg/padded_cell.inc"
	include	"source/rpg/photo_cutscene.inc"
	include	"source/rpg/scary_maze_jumpscare.inc"
	include	"source/rpg/silent_hill.inc"
	include	"source/rpg/sonic_cult.inc"
	include	"source/rpg/suspect_choose.inc"
	include	"source/rpg/data/mars.inc"
	include	"source/rpg/data/md.inc"
	include	"source/rpg/maps/maps.inc"
	include	"source/rpg/maps/routines.inc"
	include	"source/rpg/objects/ao_oni.inc"
	include	"source/rpg/objects/decor.inc"
	include	"source/rpg/objects/fog.inc"
	include	"source/rpg/objects/npc.inc"
	include	"source/rpg/objects/overlay.inc"
	include	"source/rpg/objects/player.inc"
	include	"source/rpg/objects/store_item.inc"
	include	"source/rpg/objects/tool.inc"
	include	"source/rpg/objects/warp.inc"

; ------------------------------------------------------------------------------
