; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Title screen scene 32X data header
; ------------------------------------------------------------------------------

	global MarsSpr_TitleLogos
	global MarsSpr_TitleBackground
	global MarsSpr_TitleGlitchedLogos
	global MarsPal_TitleLogos

; ------------------------------------------------------------------------------
