; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Math functions header
; ------------------------------------------------------------------------------

	global CalcTrajectory
	global CalcSine
	global SineTable
	global CalcAngle16
	global CalcAngle8
	global CalcSqrt
	global Random
	global Conv2dPointTo3d
	global Conv3dPointTo2d

; ------------------------------------------------------------------------------
