; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Palette functions header
; ------------------------------------------------------------------------------

	global LoadPalette
	global FadePaletteToBlack
	global FadePaletteToWhite
	global FadePaletteIn
	global SetPaletteFadeIntensity
	global UpdateCram

; ------------------------------------------------------------------------------
