; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Tilemap functions header
; ------------------------------------------------------------------------------

	global GetVramReadCommand
	global GetVramWriteCommand
	global GetVramDmaCommand
	global GetVramCopyCommand
	global GetCramReadCommand
	global GetCramWriteCommand
	global GetCramDmaCommand
	global GetVsramReadCommand
	global GetVsramWriteCommand
	global GetVsramDmaCommand
	global ClearVdpMemory
	global ClearVram
	global FillVram
	global ClearVramRegion
	global FillVramRegion
	global CopyVramRegion
	global ClearCram
	global FillCram
	global ClearCramRegion
	global FillCramRegion
	global ClearVsram
	global FillVsram
	global ClearVsramRegion
	global FillVsramRegion
	global DisableDisplay
	global EnableDisplay
	global ResetWindowPlanePos

; ------------------------------------------------------------------------------
