; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; RPG scene 32X data header
; ------------------------------------------------------------------------------

	global MarsSpr_RpgPlayer
	global MarsSpr_RpgOverlay
	global MarsSpr_RpgTextboxIcons
	global MarsSpr_OllieHouse
	global MarsSpr_StoreItems
	global MarsSpr_SonicCult
	global MarsSpr_SonicCultScreens
	global MarsSpr_PhotoCutscene
	global MarsSpr_Tools
	global MarsSpr_Hospital
	global MarsSpr_SuspectChoose
	global MarsSpr_AoOni
	global MarsSpr_SilentHill
	global MarsSpr_CultFrontDoor
	global MarsSpr_Prison
	global MarsSpr_PaddedCell
	global MarsSpr_GoodEnding
	global MarsSpr_RpgScaryMaze
	global MarsSpr_Burglar
	global MarsSpr_Doctor
	global MarsSpr_Cop
	global MarsSpr_Cultist
	global MarsSpr_Warden
	global MarsPal_SuspectChoose
	global MarsPal_SilentHill
	global MarsPal_CultFrontDoor
	global MarsPal_GoodEnding
	global MarsPal_RpgScaryMaze

; ------------------------------------------------------------------------------
