; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Splash screen scene Mega Drive data header
; ------------------------------------------------------------------------------

	global Art_SplashGameTapText
	global Art_SplashClownancyText
	global Art_SplashOllieText
	global Map_SplashGameTapText
	global Map_SplashClownancyText
	global Map_SplashOllieText
	global Pal_SplashText

; ------------------------------------------------------------------------------
