; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Title screen scene header
; ------------------------------------------------------------------------------
	
	include	"source/shared.inc"
	include	"source/title/variables.inc"
	include	"source/title/data/mars.inc"
	include	"source/title/data/md.inc"
	include	"source/title/maps/maps.inc"

; ------------------------------------------------------------------------------
