; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Splash screen scene 32X data header
; ------------------------------------------------------------------------------

	global MarsSpr_SplashBackground
	global MarsSpr_SplashGameTap
	global MarsSpr_SplashClownancy
	global MarsSpr_SplashOllie
	global MarsPal_SplashBackground
	global MarsPal_SplashGameTap
	global MarsPal_SplashClownancy
	global MarsPal_SplashOllie

; ------------------------------------------------------------------------------
