; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; PWM driver header
; ------------------------------------------------------------------------------

	global InitPwmDriver
	global UpdatePwmDriver
	global MarsPwmIndex
	global MarsPwmIndexEnd
	global Pwm_Silence
	global Pwm_Silence_End

; ------------------------------------------------------------------------------
