; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Interrupt functions header
; ------------------------------------------------------------------------------

	global VBlankInt
	global ClearVBlankRoutine
	global SetVBlankRoutine
	global VSync
	global WaitVSync
	global Delay

; ------------------------------------------------------------------------------
