; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sound functions header
; ------------------------------------------------------------------------------

	global PauseSound
	global UnpauseSound
	global StopSound
	global FadeSound
	global HaltSound
	global EnableAtGamesSound
	global DisableAtGamesSound
	global WaitSoundCommand
	global PlayMusic
	global PlayBackgroundSfx
	global PlaySfx

; ------------------------------------------------------------------------------
