; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; RPG stage map routines header
; ------------------------------------------------------------------------------

	global Init_OllieBedroom
	global Draw_OllieBedroom
	global Scroll_OllieBedroom
	global Init_OllieBathroom
	global Draw_OllieBathroom
	global Scroll_OllieBathroom
	global Init_OllieLivingRoom
	global Draw_OllieLivingRoom
	global Scroll_OllieLivingRoom
	global Init_OllieDiningRoom
	global Draw_OllieDiningRoom
	global Scroll_OllieDiningRoom
	global Init_OllieOutside
	global Draw_OllieOutside
	global Scroll_OllieOutside
	global Init_OllieGarage
	global Draw_OllieGarage
	global Scroll_OllieGarage
	global Init_7ElevenStreet
	global Draw_7ElevenStreet
	global Scroll_7ElevenStreet
	global Init_7ElevenStore
	global Draw_7ElevenStore
	global Scroll_7ElevenStore
	global Init_HospitalRoom
	global Draw_HospitalRoom
	global Scroll_HospitalRoom
	global Init_HospitalHallway
	global Draw_HospitalHallway
	global Scroll_HospitalHallway
	global Init_HospitalOutside
	global Draw_HospitalOutside
	global Scroll_HospitalOutside
	global Init_Prison
	global Draw_Prison
	global Scroll_Prison
	global Init_RpgScaryMaze
	global Draw_RpgScaryMaze
	global Scroll_RpgScaryMaze

; ------------------------------------------------------------------------------
