; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Error handler header
; ------------------------------------------------------------------------------

	global MasterIllegalInstr
	global MasterIllegalSlot
	global MasterCpuAddrError
	global MasterDmaAddrError
	global MasterUserBreak
	global SlaveIllegalInstr
	global SlaveIllegalSlot
	global SlaveCpuAddrError
	global SlaveDmaAddrError
	global SlaveUserBreak
	global Exception

; ------------------------------------------------------------------------------
