; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sonic stage scene header
; ------------------------------------------------------------------------------
	
	include	"source/shared.inc"
	include	"source/sonic/variables.inc"
	include	"source/sonic/ben_tear.inc"
	include	"source/sonic/collapse.inc"
	include	"source/sonic/object.inc"
	include	"source/sonic/particle.inc"
	include	"source/sonic/ring_girl_transition.inc"
	include	"source/sonic/yugioh.inc"
	include	"source/sonic/data/mars.inc"
	include	"source/sonic/data/md.inc"
	include	"source/sonic/maps/maps.inc"
	include	"source/sonic/maps/routines.inc"
	include	"source/sonic/objects/ben.inc"
	include	"source/sonic/objects/ben_boss.inc"
	include	"source/sonic/objects/blockbuster.inc"
	include	"source/sonic/objects/bridge.inc"
	include	"source/sonic/objects/button.inc"
	include	"source/sonic/objects/buzz_bomber.inc"
	include	"source/sonic/objects/chopper.inc"
	include	"source/sonic/objects/collapse_ledge.inc"
	include	"source/sonic/objects/crabmeat.inc"
	include	"source/sonic/objects/explosion.inc"
	include	"source/sonic/objects/eyeball.inc"
	include	"source/sonic/objects/monitor.inc"
	include	"source/sonic/objects/motobug.inc"
	include	"source/sonic/objects/newtron.inc"
	include	"source/sonic/objects/ollie_boss.inc"
	include	"source/sonic/objects/overlay.inc"
	include	"source/sonic/objects/path_swapper.inc"
	include	"source/sonic/objects/platform.inc"
	include	"source/sonic/objects/player.inc"
	include	"source/sonic/objects/ring_girl_boss.inc"
	include	"source/sonic/objects/rock.inc"
	include	"source/sonic/objects/slenderman_boss.inc"
	include	"source/sonic/objects/spikes.inc"
	include	"source/sonic/objects/spin_tunnel.inc"
	include	"source/sonic/objects/spring.inc"
	include	"source/sonic/objects/toad_boss.inc"
	include	"source/sonic/objects/wall.inc"

; ------------------------------------------------------------------------------
