; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sound data header
; ------------------------------------------------------------------------------

	global Song_Title
	global Song_Holiday
	global Song_Drone
	global Song_Fantasmas
	global Song_Ghz
	global Song_KissMe
	global Song_GhzGems
	global Song_Blue
	global Song_GhzSlayer
	global Song_MineEyes
	global Song_GhzGoodFuture
	global Song_GhzSin
	global Song_GhzTelefon
	global Song_Godlike
	global Song_OneHundredYears
	global Song_Promise
	global Sfx_Jump
	global Sfx_Skid
	global Sfx_Roll
	global Sfx_Dash
	global Sfx_Flash
	global Sfx_Explosion
	global Sfx_FireExplosion
	global Sfx_Collapse
	global Sfx_Spring
	global Sfx_Bounce
	global Sfx_Thump
	global Sfx_HitBoss
	global Sfx_Damage
	global Sfx_Spikes
	global Sfx_Rumble
	global Sfx_Wiggle
	global Sfx_Warp

; ------------------------------------------------------------------------------
