; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sonic scene 32X data header
; ------------------------------------------------------------------------------

	global MarsSpr_SonicPlayer
	global MarsSpr_SonicHealth
	global MarsSpr_SonicOverlay
	global MarsSpr_SonicMonitor
	global MarsSpr_SonicPlatform
	global MarsSpr_SonicPlatformAlt
	global MarsSpr_SonicPlatformComputer
	global MarsSpr_SonicRock
	global MarsSpr_SonicBridge
	global MarsSpr_SonicBridgeAlt
	global MarsSpr_SonicBridgeBen
	global MarsSpr_SonicSpikes
	global MarsSpr_SonicSpring
	global MarsSpr_SonicExplosion
	global MarsSpr_SonicMotobug
	global MarsSpr_SonicBuzzBomber
	global MarsSpr_SonicCrabmeat
	global MarsSpr_SonicChopper
	global MarsSpr_SonicNewtron
	global MarsSpr_SonicButton
	global MarsSpr_Blockbuster
	global MarsSpr_RingGirlRotoscope
	global MarsSpr_OllieWakeUp
	global MarsSpr_RingGirlBoss
	global MarsSpr_RingGirlBossBg
	global MarsSpr_SonicBen
	global MarsSpr_SonicEyeball
	global MarsSpr_BenBackground
	global MarsSpr_BenBossSprites
	global MarsSpr_SlendermanBoss
	global MarsSpr_ToadBoss
	global MarsSpr_OllieBoss
	global MarsSpr_OllieHand
	global MarsSpr_BenTear
	global MarsPal_RingGirl
	global MarsPal_RingGirlBoss
	global MarsPal_BenDrowned
	global MarsPal_BenBackground
	global MarsPal_BenDrownedBoss
	global MarsPal_Slenderman
	global MarsPal_SlendermanBoss
	global MarsPal_Hellscape
	global MarsPal_HellscapeBoss
	global MarsPal_ScaryMaze
	global MarsPal_FinalNormal
	global MarsPal_FinalPrison
	global MarsPal_FinalComputer
	global MarsPal_OllieBoss

; ------------------------------------------------------------------------------
