; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sonic scene Mega Drive data header
; ------------------------------------------------------------------------------

	global Art_Health
	global Art_YugiohCard
	global Art_CollapseLedge
	global Art_Wall
	global Art_GhzSunflower
	global Art_GhzFlower
	global Art_GhzWaterfall
	global Art_GhzFlowerStalk
	global Art_SlendermanBg
	global Spr_Health
	global Spr_CollapseLedge
	global Spr_Wall

; ------------------------------------------------------------------------------
