; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Configuration
; ------------------------------------------------------------------------------

DEBUG			equ 0					; Debug build
GAME_TITLE		equs "GameTap, Cup Noodles, and Bitter Tears"
COPYRIGHT		equs "OLLIE"				; Copyright holder
REVISION		equ 0					; Revision

; ------------------------------------------------------------------------------
