; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Shared header
; ------------------------------------------------------------------------------

	include	"source/framework/md.inc"
	include	"source/common/script.inc"
	include	"source/common/data/mars.inc"
	include	"source/common/data/md.inc"
	include	"source/sound/sound_data.inc"
	
; ------------------------------------------------------------------------------

	global Main
	global SplashScreenScene
	global TitleScreenScene
	global SonicStageScene
	global RpgStageScene
	global ResumeRpgStageScene
	global CreditsScene

; ------------------------------------------------------------------------------
