; ------------------------------------------------------------------------------
; GameTap 32X
; By Ollie_Ollie_TechDeck
; ------------------------------------------------------------------------------
; Sonic object functions header
; ------------------------------------------------------------------------------

	global HazardObject
	global InstaKillObject
	global BadnikObject
	global BossObject
	global BossObjectNoHazard

; ------------------------------------------------------------------------------
